{
 "title": "Polly metrics dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "TypiCode Comments Retry Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(resilience_polly_strategy_events{pipeline_name=\"TypiCodeCommentsRetryPipeline\", event_name=\"OnRetry\"})",
     "legendFormat": "{{event_name}}"
    }
   ]
  },
  {
   "title": "TypiCode Comments Retries Events",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(event_name) (resilience_polly_strategy_events{pipeline_name=\"TypiCodeCommentsRetryPipeline\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TypiCode Comments Retry Exceptions",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(exception_type) (resilience_polly_strategy_events{pipeline_name=\"TypiCodeCommentsRetryPipeline\", event_name=\"OnRetry\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg duration of every retry attempt",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 15, "y": 0 },
   "targets": [
    {
     "expr": "sum by(attempt_number) (rate(resilience_polly_strategy_attempt_duration_sum{pipeline_name=\"TypiCodeCommentsRetryPipeline\"}[30m])) / sum by(attempt_number) (rate(resilience_polly_strategy_attempt_duration_count{pipeline_name=\"TypiCodeCommentsRetryPipeline\"}[30m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TypiCode Users CircuitBreaker Status",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(event_name) (resilience_polly_strategy_events{pipeline_name=\"TypiCodeUsersCircuitBreakerPipeline\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TypiCode Users Circuit Breaker Pipeline Avg Duration",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 14, "x": 5, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "resilience_polly_pipeline_duration_sum{pipeline_name=\"TypiCodeUsersCircuitBreakerPipeline\"} / resilience_polly_pipeline_duration_count{pipeline_name=\"TypiCodeUsersCircuitBreakerPipeline\"}",
     "legendFormat": "{{exception_type}} {{event_name}}"
    }
   ]
  }
 ]
}